apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bsm841q3n-python
  janus-idp.io/tekton: bsm841q3n-python
  backstage.io/kubernetes-id: bsm841q3n-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bsm841q3n-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
